### ISSUE TITLE
Fixing the error when call "collider:destroy()"

### ISSUE THREAD

**Issue by DadsamG** [4v0v/physics#5]
The `collider:destroy()` is causing some errors:

4v0v.lua:424: attempt to call method 'remove_shape' (a nil value)

*error code*: `function Shape:destroy() self._collider:remove_shape(self._tag) end`
**fixed code**: `function Shape:destroy() self._collider:removeShape(self._tag) end`

**Comment by 4v0v** [comment]
corrected, thanks
